import { initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import * as functions from 'firebase-functions'

const app = initializeApp()
export const db = getFirestore(app)

export const taxify = functions.https.onRequest((req, res) => {
  // Handle HTTP requests here.
  res.send('Hello from Taxfy Functions!')
})

export {
  // This part is automatically generated by Taxfy Framework.
  // Please do not edit this part.
  // Taxfy Doc: https://taxfy.dev
  addStreamUserChatRoomMessage,
  addVertexMessage,
  createUserChatRoom,
  addUserChatRoomMessage,
  createSignInData,
  verifySIWS,
} from './routings'
