import admin from 'firebase-admin'
import { dotenv } from '@taxify-framework/utils'

dotenv.config()
admin.initializeApp()
export const db = admin.firestore()

export {
  // This part is automatically generated by Taxify Framework.
  // Please do not edit this part.
  // Taxify Doc: https://taxify.dev
  addStreamUserChatRoomMessage,
  addVertexMessage,
  createUserChatRoom,
  addUserChatRoomMessage,
  createSignInData,
  verifySIWS,
} from '@/routings'
